<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Individual penalty charges applied to a loan. Not auto-generated by
     * a background job — staff apply them manually (per the BKR spec's
     * "Add/Remove Penalty" transaction), using loan_penalty_settings as a
     * pre-filled default amount. "Removed" is a soft flag rather than a
     * hard delete, same audit-safety principle used everywhere else in
     * this app (payments, journal entries): the charge and its removal
     * both stay visible on the loan's history.
     */
    public function up(): void
    {
        if (!Schema::hasTable('loan_penalties')) {
            Schema::create('loan_penalties', function (Blueprint $table) {
                $table->id();
                $table->foreignId('loan_id')->constrained('loans')->onDelete('cascade');
                $table->foreignId('loan_manager_id')->constrained('loan_managers')->onDelete('cascade');
                $table->decimal('amount', 15, 2);
                $table->text('reason')->nullable();
                $table->foreignId('applied_by')->nullable()->constrained('users')->nullOnDelete();

                $table->boolean('is_removed')->default(false);
                $table->foreignId('removed_by')->nullable()->constrained('users')->nullOnDelete();
                $table->timestamp('removed_at')->nullable();
                $table->text('removal_reason')->nullable();

                $table->timestamps();
            });
        }
    }

    public function down(): void
    {
        Schema::dropIfExists('loan_penalties');
    }
};
